const arrayHeadCategoies = [
    {"TypeID":"28","Description":"Action","OrderPriority":"10"},
    {"TypeID":"29","Description":"Adventure","OrderPriority":"12"},
    {"TypeID":"30","Description":"Arcade","OrderPriority":"14"},
    {"TypeID":"31","Description":"Art & Design","OrderPriority":"16"},
    {"TypeID":"32","Description":"Auto & Vehicles","OrderPriority":"18"},
    {"TypeID":"33","Description":"Beauty","OrderPriority":"20"},
    {"TypeID":"34","Description":"Board","OrderPriority":"22"},
    {"TypeID":"35","Description":"Books","OrderPriority":"24"},
    {"TypeID":"19","Description":"Books & Reference","OrderPriority":"26"},
    {"TypeID":"2","Description":"Business","OrderPriority":"28"},
    {"TypeID":"36","Description":"Card","OrderPriority":"30"},
    {"TypeID":"37","Description":"Casino","OrderPriority":"32"},
    {"TypeID":"38","Description":"Casual","OrderPriority":"34"},
    {"TypeID":"40","Description":"Catalogs","OrderPriority":"36"},
    {"TypeID":"12","Description":"Comics","OrderPriority":"38"},
    {"TypeID":"14","Description":"Communication","OrderPriority":"40"},
    {"TypeID":"41","Description":"Dating","OrderPriority":"42"},
    {"TypeID":"42","Description":"Dice","OrderPriority":"44"},
    {"TypeID":"10","Description":"E-Commerce","OrderPriority":"50"},
    {"TypeID":"3","Description":"Education","OrderPriority":"60"},
    {"TypeID":"43","Description":"Educational","OrderPriority":"62"},
    {"TypeID":"5","Description":"Entertainment","OrderPriority":"70"},
    {"TypeID":"44","Description":"Events","OrderPriority":"72"},
    {"TypeID":"45","Description":"Family","OrderPriority":"74"},
    {"TypeID":"16","Description":"Finance","OrderPriority":"80"},
    {"TypeID":"46","Description":"Food & Drink","OrderPriority":"82"},
    {"TypeID":"1","Description":"Games","OrderPriority":"90"},
    {"TypeID":"9","Description":"Health and Fitness","OrderPriority":"100"},
    {"TypeID":"47","Description":"House & Home","OrderPriority":"102"},
    {"TypeID":"48","Description":"Kids","OrderPriority":"104"},
    {"TypeID":"11","Description":"Libreries and demo","OrderPriority":"110"},
    {"TypeID":"4","Description":"LifeStyle","OrderPriority":"120"},
    {"TypeID":"49","Description":"Maps & Navigation","OrderPriority":"122"},
    {"TypeID":"21","Description":"Media and video","OrderPriority":"130"},
    {"TypeID":"20","Description":"Medical","OrderPriority":"140"},
    {"TypeID":"8","Description":"Music","OrderPriority":"150"},
    {"TypeID":"50","Description":"Music & Audio","OrderPriority":"152"},
    {"TypeID":"51","Description":"Navigation","OrderPriority":"154"},
    {"TypeID":"52","Description":"News","OrderPriority":"156"},
    {"TypeID":"22","Description":"News and magazines","OrderPriority":"160"},
    {"TypeID":"53","Description":"Parenting","OrderPriority":"162"},
    {"TypeID":"23","Description":"Personalization","OrderPriority":"170"},
    {"TypeID":"54","Description":"Photo & Video","OrderPriority":"172"},
    {"TypeID":"17","Description":"Photography","OrderPriority":"180"},
    {"TypeID":"24","Description":"Productivity","OrderPriority":"190"},
    {"TypeID":"55","Description":"Puzzle","OrderPriority":"192"},
    {"TypeID":"56","Description":"Racing","OrderPriority":"194"},
    {"TypeID":"57","Description":"Reference","OrderPriority":"196"},
    {"TypeID":"58","Description":"Role","OrderPriority":"198"},
    {"TypeID":"59","Description":"Role Playing","OrderPriority":"199"},
    {"TypeID":"13","Description":"Shopping","OrderPriority":"200"},
    {"TypeID":"60","Description":"Simulation","OrderPriority":"202"},
    {"TypeID":"25","Description":"Social","OrderPriority":"210"},
    {"TypeID":"61","Description":"Social Networking","OrderPriority":"212"},
    {"TypeID":"15","Description":"Sports","OrderPriority":"220"},
    {"TypeID":"62","Description":"Strategy","OrderPriority":"222"},
    {"TypeID":"18","Description":"Tools","OrderPriority":"230"},
    {"TypeID":"27","Description":"Transportation","OrderPriority":"240"},
    {"TypeID":"7","Description":"Travel","OrderPriority":"250"},
    {"TypeID":"63","Description":"Travel & Local","OrderPriority":"252"},
    {"TypeID":"64","Description":"Trivia","OrderPriority":"254"},
    {"TypeID":"6","Description":"Utilities","OrderPriority":"260"},
    {"TypeID":"65","Description":"Video Players & Editors","OrderPriority":"262"},
    {"TypeID":"26","Description":"Weather","OrderPriority":"270"},
    {"TypeID":"66","Description":"Word","OrderPriority":"272"},
    {"TypeID":"99","Description":"Other","OrderPriority":"999"}
]

export default arrayHeadCategoies;